### ISSUE TITLE
knitr package  for report generation

### ISSUE THREAD

**Issue by arhik** [lfiondella/SRT#18]
Take a look at knitr package. This could be used for auto report generation. Please take a look at this and let me know.

**Comment by arhik** [comment]
https://cran.r-project.org/web/packages/knitr/knitr.pdf

The above link is documentation of knitr package

**Comment by vnagaraju14** [comment]
Karthik, This solves the issue in saving any form of data rite

**Comment by arhik** [comment]
yes, It has many options LATEX, markdown .....Rmarkdown is probably best for us. Its limited but faster to learn

**Comment by DanGarcia595** [comment]
Is this package need for internal use or are we using this to send the customer the file on demand?

**Comment by arhik** [comment]
This task is done. Knitr was ignored. But a milestone which was actually accomplished still stays there. So lets close this.

Thank you @DanGarcia595 for your work.
