### ISSUE TITLE
DSS estimated time for next n failures goes negative.

### ISSUE THREAD

**Issue by arhik** [lfiondella/SRT#22]

**Comment by a1729nikora** [comment]
It looks to me like a negative number means that there are no more failures to be seen.  I've seen this in making predictions for SYS1 in a situation where there were 136 failures observed and an expected total number of 136.9... failures remaining.  I fixed this by adding a check in the right function in "Detailed_predictions.R" to see if the estimated time to the next failure ever goes negative.  If it does, I return "NA".

**Comment by arhik** [comment]
You mean you fixed it. If you fixed it. Please send a pull request with tagging this issue like 'Fixes #22'.

**Comment by arhik** [comment]
Allen fixed it in https://github.com/lfiondella/SRT/commit/11eece12edaed0eb4b47c04fc969569b044abb87
