### ISSUE TITLE
JM has NA in its table

### ISSUE THREAD

**Issue by arhik** [lfiondella/SRT#24]
![image](https://cloud.githubusercontent.com/assets/5755530/10379687/b660912a-6ddd-11e5-80da-33cf5a9aae40.png)

After Integration Plotting is seriously inconsistent. JM is consistent in not showing up. The image explains why.

Other plots of MVF will be displayed only when we transition from tables. There is major conflict somewhere which should be resolved.

**Comment by a1729nikora** [comment]
Thanks, Karthik.  I think what you’ve found here is an instance in which JM did not converge during parameter estimation – note the “NaN” entries for JM parameters 1 and 2 in the third and fourth lines of the table.  When a model’s parameter estimates don't converge, we don’t plot the results, and the other model estimates/predictions are set to NaN.  We can go over this tomorrow, but I think it’s behavior that we would expect.

I’d need to know the dataset on which you ran this and what the model configuration settings were.

Regards,
Allen N.

# 

   Allen P. Nikora, Ph.D.
   Program Element Manager,
        Assurance Technology Program Office Software Element

   Jet Propulsion Laboratory
   California Institute of Technology
   4800 Oak Grove Drive
   Pasadena, CA  91109-8099
   Mail Stop 125-233

   vox: 818.393.1104
   fax: 818.393.1362
   email: Allen.P.Nikora@jpl.nasa.gov

#

**Comment by arhik** [comment]
Its SYS1 dataset. It should converge as far i know. @vnagaraju14 Please verify this.

**Comment by vnagaraju14** [comment]
Yes, JM converges for SYS1 dataset. 

----- Original Message -----
