### ISSUE TITLE
GO_BM_FT.R

### ISSUE THREAD

**Issue by vnagaraju14** [lfiondella/SRT#33]
Please Comment here if you have any questions

**Comment by bdavs** [comment]
Already commented

**Comment by JT0496** [comment]
This is what I wrote up trying to add in some comments that are "in English". I'm not 100% positive about the accuracy of all of the comments' correctness.
[GO_BM_FT.txt](https://github.com/lfiondella/SRT/files/15408/GO_BM_FT.txt)
