### ISSUE TITLE
Laplace trend test UI changes.

### ISSUE THREAD

**Issue by arhik** [lfiondella/SRT#51]
The following are the changes made in UI. This is more like a discussion forum rather than an issue. Cons and Pros will be discussed.

![image](https://cloud.githubusercontent.com/assets/5755530/10501145/71b8f700-72ac-11e5-8b9b-bc142566d4b9.png)

![image](https://cloud.githubusercontent.com/assets/5755530/10501156/8941904e-72ac-11e5-981d-e3eb0b9ab491.png)

The

**Comment by arhik** [comment]
I like it. Its simpler. I dont like the idea that i will have change the number at the same time. I prefer to have the previous line with slight transparency(alpha channel). I have a mixed opinion here. I would like to know what you people think.

@lfiondella @vnagaraju14 @a1729nikora

**Comment by lfiondella** [comment]
I suggest the standard confidence levels we had, plus the custom value Allen added. 

----- Original Message -----

**Comment by a1729nikora** [comment]
That sounds like a good possibility!  I’ll take a look and get back to you.  Right now I’m installing Rstudio and R on my Windows 7 partition, trying to figure out what’s going on with some types of plots not being able to be saved in Windows.

-Allen N.

# 

   Allen P. Nikora, Ph.D.
   Program Element Manager,
        Assurance Technology Program Office Software Element

   Jet Propulsion Laboratory
   California Institute of Technology
   4800 Oak Grove Drive
   Pasadena, CA  91109-8099
   Mail Stop 125-233

   vox: 818.393.1104
   fax: 818.393.1362
   email: Allen.P.Nikora@jpl.nasa.gov

#

**Comment by a1729nikora** [comment]
It’s amazingly slow on my Windows partition – I could probably go faster with an abacus!  I’ll let you know what I find…

-Allen N.

# 

   Allen P. Nikora, Ph.D.
   Program Element Manager,
        Assurance Technology Program Office Software Element

   Jet Propulsion Laboratory
   California Institute of Technology
   4800 Oak Grove Drive
   Pasadena, CA  91109-8099
   Mail Stop 125-233

   vox: 818.393.1104
   fax: 818.393.1362
   email: Allen.P.Nikora@jpl.nasa.gov

# 

From: Allen Nikora <Allen.P.Nikora@jpl.nasa.gov<mailto:Allen.P.Nikora@jpl.nasa.gov>>
Date: Wednesday, October 14, 2015 at 6:13 PM
To: lfiondella/SRT <reply@reply.github.com<mailto:reply@reply.github.com>>, lfiondella/SRT <SRT@noreply.github.com<mailto:SRT@noreply.github.com>>
Subject: Re: [SRT] Laplace trend test UI changes. (#51)

That sounds like a good possibility!  I’ll take a look and get back to you.  Right now I’m installing Rstudio and R on my Windows 7 partition, trying to figure out what’s going on with some types of plots not being able to be saved in Windows.

-Allen N.

# 

   Allen P. Nikora, Ph.D.
   Program Element Manager,
        Assurance Technology Program Office Software Element

   Jet Propulsion Laboratory
   California Institute of Technology
   4800 Oak Grove Drive
   Pasadena, CA  91109-8099
   Mail Stop 125-233

   vox: 818.393.1104
   fax: 818.393.1362
   email: Allen.P.Nikora@jpl.nasa.gov

#

**Comment by arhik** [comment]
We resolved this conservation.
