### ISSUE TITLE
Error when applying model

### ISSUE THREAD

**Issue by epires3** [lfiondella/SRT#60]
Whenever I try to run the application on my system, I keep getting this error message after applying a model.

Warning: Unhandled error in observer: invalid argument to unary operator
observeEvent(input$runModels)
ERROR: [on_request_read] connection reset by peer

I am running this on a Windows 10 64-bit platform.

Any help would be greatly appreciated.

**Comment by a1729nikora** [comment]
I just saw this behavior this morning on a Mac OS X system.  I'm on a MacBook Pro running Mac OS X 10.10.5, R 3.2.2, and RStudio 0.99.482.  I saw the message once, tried running the models again, and the models ran.  I don't have any answer yet, but this is the first time I've seen this behavior.

**Comment by arhik** [comment]
This is an error which was resolved by re pushing entire code . This was interesting bug. I couldn't make head and tail of it. but this is resolved. i am closing. Please update your local repositories.
