### ISSUE TITLE
Delete Parameter Interval Estimation End Point Slider?

### ISSUE THREAD

**Issue by a1729nikora** [lfiondella/SRT#61]
Since we're not using variable parameter estimation intervals for this version, should we delete it, or at least hide it from the user, to avoid confusion?

**Comment by lfiondella** [comment]
Hide by commenting. We may implement it in the future. 

----- Original Message -----

**Comment by a1729nikora** [comment]
That's what I was thinking, too, Lance - done!

-Allen N.

# 

   Allen P. Nikora, Ph.D.
   Program Element Manager,
        Assurance Technology Program Office Software Element

   Jet Propulsion Laboratory
   California Institute of Technology
   4800 Oak Grove Drive
   Pasadena, CA  91109-8099
   Mail Stop 125-233

   vox: 818.393.1104
   fax: 818.393.1362
   email: Allen.P.Nikora@jpl.nasa.gov

#

**Comment by arhik** [comment]
This is fixed. I am closing this.
