### ISSUE TITLE
Suggest Delaying Saving Tabs 3 and 4 as PDF for Next Version

### ISSUE THREAD

**Issue by a1729nikora** [lfiondella/SRT#62]
I'd like comments on delaying the "save as pdf" capability for Tabs 3 and 4 until the next release.  We can save them as CSV right now, and I'd like to get what we've got to Thierry as soon as we can.  What are your thoughts?

**Comment by lfiondella** [comment]
So long as the intermediate product is complete and consistent we can freeze the merging of functionality soon. Thierry is out of town this week as are Vidhya and I. We can communicate via email this week and have a phone discussion at the beginning of next week. Thierry was planning on visiting UMass next Monday and Tuesday. 

----- Original Message -----

**Comment by a1729nikora** [comment]
I think I've figured out knitr and R markdown.  I'll work on it this weekend, and we may have pdf after all.

**Comment by a1729nikora** [comment]
The tables on Tabs 3 and 4 can now be saved as pdf using knitr.

**Comment by arhik** [comment]
Great, Thanks for good news. I had a plan of entire report in one go 
using knitr. May be in next release.

Karthik.

**Comment by arhik** [comment]
I confirm its working. I can close this.
