### ISSUE TITLE
Time Required to Achieve Target Reliability Needs to be Integrated

### ISSUE THREAD

**Issue by a1729nikora** [lfiondella/SRT#63]
For Tab 3, the computations to predict the additional amount of time required to achieve a specified target reliability for a specified mission length need to be integrated.  The computations are already available in the individual source files that implement the models.

**Comment by a1729nikora** [comment]
Existing computations have been integrated in my local branch.  I'm running tests to see if the computations produce the expected results before I push the code/make a pull request.

**Comment by arhik** [comment]
Let me know if this is fixed completely.

**Comment by a1729nikora** [comment]
Closed - integration is complete.

**Comment by a1729nikora** [comment]
Now I'm really closing it...
