### ISSUE TITLE
Model Query on Tab 3 Doesn't Subset Data

### ISSUE THREAD

**Issue by a1729nikora** [lfiondella/SRT#69]
When a subset of the data is applied to models, the detailed queries done on Tab 3 still use the entire data set instead of the subset.

**Comment by a1729nikora** [comment]
Corrected to subset data to which detailed model queries are applied.

**Comment by arhik** [comment]
With your permission can i close this if its fixed already?

**Comment by a1729nikora** [comment]
I'm closing it now.
